# Generated by Django 5.2.18 on 2026-10-08 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cadeau",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="nom")),
                ("photo", models.URLField(blank=True)),
                ("link", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="prix",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cadeaux",
                "ordering": ["id"],
            },
        ),
    ]
