# Generated by Django 5.2.18 on 2026-10-08 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("birthlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cadeau",
            name="bought_by",
            field=models.ManyToManyField(blank=True, related_name="bought", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="cadeau",
            name="interested_families",
            field=models.ManyToManyField(blank=True, related_name="interested", to=settings.AUTH_USER_MODEL),
        ),
    ]
