# Generated by Django 5.2.18 on 2026-10-08 10:24

import django.utils.timezone
from django.db import migrations, models

import offrants.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offrant",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=offrants.models._random_uuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "invitation_id",
                    models.CharField(
                        db_index=True, default=offrants.models._random_uuid, editable=False, max_length=32, unique=True
                    ),
                ),
                ("invitation_sent", models.DateTimeField(blank=True, default=None, null=True)),
                ("invitation_opened", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "rsvp_id",
                    models.CharField(
                        db_index=True, default=offrants.models._random_uuid, editable=False, max_length=32, unique=True
                    ),
                ),
                ("rsvp_sent", models.DateTimeField(blank=True, default=None, null=True)),
                ("rsvp_opened", models.DateTimeField(blank=True, default=None, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "invité",
                "verbose_name_plural": "invités",
                "ordering": ["first_name", "last_name"],
            },
            managers=[
                ("objects", offrants.models.OffrantManager()),
            ],
        ),
    ]
